// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqSFxsXMDj3X_eSLvN8DzFkeI7cembPQ',
    appId: '1:1009645628684:web:708a71d6cc1f5823b36d29',
    messagingSenderId: '1009645628684',
    projectId: 'flutterauthentication-40d3b',
    authDomain: 'flutterauthentication-40d3b.firebaseapp.com',
    storageBucket: 'flutterauthentication-40d3b.firebasestorage.app',
    measurementId: 'G-6KPH2JQ2D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQA2gwY0nEs4nyXU_3DANcULyc4Dpnno',
    appId: '1:1009645628684:android:51756b54b695867db36d29',
    messagingSenderId: '1009645628684',
    projectId: 'flutterauthentication-40d3b',
    storageBucket: 'flutterauthentication-40d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsjydowIBZ_A6hI1192jTrO_hnlR9Kjo',
    appId: '1:1009645628684:ios:367a53c1e56b51b0b36d29',
    messagingSenderId: '1009645628684',
    projectId: 'flutterauthentication-40d3b',
    storageBucket: 'flutterauthentication-40d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWsjydowIBZ_A6hI1192jTrO_hnlR9Kjo',
    appId: '1:1009645628684:ios:367a53c1e56b51b0b36d29',
    messagingSenderId: '1009645628684',
    projectId: 'flutterauthentication-40d3b',
    storageBucket: 'flutterauthentication-40d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterauthentication',
  );
}
